version: '3.5'

services:

  db:
    container_name: container-database-blog
    image: postgres:latest
    restart: always
    env_file:
      - db.env
    ports:
      - "5432:5432"
    volumes:
      - db_data:/var/lib/postgresql/data

volumes:
  db_data: {}